### ISSUE TITLE
remove this project it doesn't work and its not maintained

### ISSUE THREAD

**Issue by startswithaj** [jasmine-contrib/grunt-jasmine-node#65]

**Comment by s9tpepper** [comment]
Why should I remove it? I am actively using it in my projects. It works fine for me. If you don't like it or it doesn't work for you find another project. I don't have to remove it if it doesn't work for you.

**Comment by startswithaj** [comment]
I recommend using this for anyone thats interested.

https://www.npmjs.com/package/grunt-jasmine-node-new

github.com/lennym/grunt-jasmine-node
